### ISSUE TITLE
Who But God is the Witness Summer 2023 Publication Thread

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/shenoute-canons8-dev#3]
- [x] shenoute.witness.FL185-186
    - [x] linguistic annotation
    - [x] chapter_n
    - [x] verse_n/sentence division
    - [x] pb_xml_id
    - [x] entities
    - [x] identities
    - [x] indexing and metadata
    - [x]  editorial review by @ctschroeder
    - [x]  [REVIEW PUBLICATION CHECKLIST](https://wiki.copticscriptorium.org/doku.php?id=checklist_for_publishing_corpora)

**Comment by ctschroeder** [comment]
@LCBM0828 the annotations for this look good. We need sentence splitting

**Comment by LCBM0828** [comment]
Added sentence splits and chapters following AB translation/sentence breaks.

**Comment by ctschroeder** [comment]
@LCBM0828 I looked at the ms and took photos in Naples. I did note ekthesis in GitDox. Looks like it averages 3 per page. I can't remember if we needed that info for this one or not but here it is

**Comment by ctschroeder** [comment]
this is done
