### ISSUE TITLE
Winter/Spring 2024 Release Thread

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/shenoute-canons8-dev#4]
- [x] shenoute.crushed.FL125-132
    - [x] linguistic annotation
    - [x] chapter_n
    - [x] verse_n/sentence division
    - [x] pb_xml_id
    - [x] entities
    - [x] identities
    - [x] indexing and metadata
    - [x]  editorial review by @ctschroeder
    - [x]  [REVIEW PUBLICATION CHECKLIST](https://wiki.copticscriptorium.org/doku.php?id=checklist_for_publishing_corpora)

- [x] shenoute.crushed.FL133-140
    - [x] linguistic annotation
    - [x] chapter_n
    - [x] verse_n/sentence division
    - [x] pb_xml_id
    - [x] entities
    - [x] identities
    - [x] indexing and metadata
    - [x]  editorial review by @ctschroeder
    - [x]  [REVIEW PUBLICATION CHECKLIST](https://wiki.copticscriptorium.org/doku.php?id=checklist_for_publishing_corpora)

**Comment by LCBM0828** [comment]
@ctschroeder I have completed the chapter/versification of FL 132-140. AB is a beautiful translator!

**Comment by ctschroeder** [comment]
I have added small notes about ekthesis, column breaks, Amélineau's reconstructions to 125-132 and 133-140 based on the manuscript in Naples. Did not create a full diplomatic edition

**Comment by ctschroeder** [comment]
this is done
